const postConstants = {
  POSTS_ACTION_START: "POSTS_ACTION_START",
  GET_SINGLE_POST_SUCCESS: "GET_SINGLE_POST_SUCCESS",
  GET_SINGLE_POST_FAILURE: "GET_SINGLE_POST_FAILURE",
  CLEAR_SINGLE_POST: "CLEAR_SINGLE_POST",
  GET_LATEST_POSTS_SUCCESS: "GET_LATEST_POSTS_SUCCESS",
  GET_LATEST_POSTS_FAILURE: "GET_LATEST_POSTS_FAILURE",
  GET_MY_POSTS_SUCCESS: "GET_MY_POSTS_SUCCESS",
  GET_MY_POSTS_FAILURE: "GET_MY_POSTS_FAILURE",
  GET_WISH_LIST_POSTS_SUCCESS: "GET_WISH_LIST_POSTS_SUCCESS",
  GET_WISH_LIST_POSTS_FAILURE: "GET_WISH_LIST_POSTS_FAILURE",
  GET_RELATED_POSTS_SUCCESS: "GET_RELATED_POSTS_SUCCESS",
  GET_RELATED_POSTS_FAIL: "GET_RELATED_POSTS_FAIL",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAILURE: "ADD_POST_FAILURE",
  CLEAR_ADD_POST: "CLEAR_ADD_POST",
};

export default postConstants;
