const postConstants = {
  POSTS_ACTION_START: "POSTS_ACTION_START",
  GET_SINGLE_POST_SUCCESS: "GET_SINGLE_POST_SUCCESS",
  GET_SINGLE_POST_FAILURE: "GET_SINGLE_POST_FAILURE",
  GET_LATEST_POSTS_SUCCESS: "GET_LATEST_POSTS_SUCCESS",
  GET_LATEST_POSTS_FAILURE: "GET_LATEST_POSTS_FAILURE",
  GET_MY_POSTS_SUCCESS: "GET_MY_POSTS_SUCCESS",
  GET_MY_POSTS_FAILURE: "GET_MY_POSTS_FAILURE",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
};

export default postConstants;
