const userConstants = {
  USER_ACTION_START: "USER_ACTION_START",
  POST_LOGIN_SUCCESS: "POST_LOGIN_SUCCESS",
  POST_LOGIN_FAIL: "POST_LOGIN_FAIL",
  AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",
  AUTHENTICATION_FAIL: "AUTHENTICATION_FAIL",
};

export default userConstants;
