const userConstants = {
  USER_ACTION_START: "USER_ACTION_START",
  POST_LOGIN_SUCCESS: "POST_LOGIN_SUCCESS",
  POST_LOGIN_FAIL: "POST_LOGIN_FAIL",
  AUTHENTICATION_SUCCESS: "AUTHENTICATION_SUCCESS",
  AUTHENTICATION_FAIL: "AUTHENTICATION_FAIL",
  DELETE_ACCOUNT_SUCCESS: "DELETE_ACCOUNT_SUCCESS",
  DELETE_ACCOUNT_FAIL: "DELETE_ACCOUNT_FAIL",
  UPDATE_ACCOUNT_SUCCESS: "UPDATE_ACCOUNT_SUCCESS",
  UPDATE_ACCOUNT_FAIL: "UPDATE_ACCOUNT_FAIL",
  LOG_OUT: "LOG_OUT",
};

export default userConstants;
